### PR TITLE
Expand README

### PR DESCRIPTION
**Pull request by umaint**
Add four screenshots and installation instructions for Ubuntu Server 18.04 LTS

### CODE REVIEW

**Comment by GreaterFire** [comment]
Some other developers and I thought this tutorial is too specific for readme and thus should be put in the wiki.

**Comment by umaint** [comment]
Do you have a link to the wiki?

**Comment by GreaterFire** [comment]
https://github.com/trojan-gfw/trojan-panel/wiki

**Comment by umaint** [comment]
Done! https://github.com/trojan-gfw/trojan-panel/wiki/Installation-on-Ubuntu-18.04-LTS

**Comment by GreaterFire** [comment]
Thanks for your contribution! I'll close this pr.

**Pull request closed without merging**
